dist: bionic

before_install:
  # install bazel
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install bazel
  # install clang-format
  - sudo apt install clang-format
  - clang-format --version

script:
  - find . -name "*.h" -o -name "*.cpp" -exec clang-format -i {} \;
  - git diff --exit-code
  - bazel test //...
